"""Generate docs/MEASURED-PERFORMANCE.md from the measured-results logs.

NEXUS's honesty standard: performance numbers quoted anywhere must come from
a measurement artifact, not from memory or marketing. This script is the
single path from artifacts to prose -- it reads the JSON the honest gates
wrote and renders the document, so the numbers cannot drift from the logs.

    python tools/gen_performance_doc.py           # (re)write the document
    python tools/gen_performance_doc.py --check   # exit 1 if the doc is stale

Missing artifacts render as an explicit "NO MEASUREMENT ARTIFACT" section:
the generator never fills gaps with remembered numbers.
"""
import argparse
import json
import os
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGS = os.path.join(ROOT, "logs")
DOC = os.path.join(ROOT, "docs", "MEASURED-PERFORMANCE.md")

SEAT_NAMES = {
    "volumetric": "Volumetric Vanguard (rates & floods)",
    "recon": "Recon Inquisitor (flags & scans)",
    "payload": "Deep-Payload Analyst (entropy & C2)",
}


def load(name):
    path = os.path.join(LOGS, name)
    if not os.path.exists(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def fmt_ts(raw):
    if not raw:
        return "unknown time"
    try:
        dt = datetime.fromisoformat(str(raw))
    except ValueError:
        return str(raw)
    # Artifacts are written with naive local timestamps (datetime.now()).
    # Converting with astimezone() would assume the READER's local zone and
    # render differently on a UTC CI runner than on the writer's machine,
    # breaking doc freshness. Render deterministically: naive times carry no
    # zone claim; only tz-aware stamps are converted to UTC.
    if dt.tzinfo is None:
        return dt.strftime("%Y-%m-%d %H:%M (writer-local)")
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def pct(x):
    if x is None:
        return "n/a"
    return f"{100.0 * float(x):.2f}%"


def render() -> str:
    lines = []
    add = lines.append
    add("# NEXUS - Measured Performance")
    add("")
    add("> Generated by `tools/gen_performance_doc.py` from the JSON artifacts in")
    add("> `logs/`. **Do not edit by hand**: every number is traceable to a")
    add("> measurement artifact and its timestamp. Re-run the script after any")
    add("> training or benchmark run (`--check` fails if the doc is stale).")
    add("")

    # ---- honest training gate -------------------------------------------
    honest = load("honest_training_results.json")
    add("## Honest training gate (`logs/honest_training_results.json`)")
    add("")
    if honest is None:
        add("**NO MEASUREMENT ARTIFACT.** Run `train_honest.py` first.")
        add("")
    else:
        add(f"Measured {fmt_ts(honest.get('timestamp'))}. "
            f"Operating point: **{honest.get('operating_point', 'n/a')}** "
            "(owner: `policy.py`). Promotion gate: "
            f"**{'PASSED' if honest.get('promoted') else 'NOT PASSED'}**.")
        add("")
        add("| Detector | Holdout TPR | Holdout FPR | Seated |")
        add("|---|---|---|---|")
        mono = honest.get("monolith") or {}
        add(f"| Monolith | {pct(mono.get('holdout_tpr'))} | "
            f"{pct(mono.get('holdout_fpr'))} | - |")
        for key, seat in (honest.get("specialists") or {}).items():
            add(f"| {SEAT_NAMES.get(key, key)} | {pct(seat.get('holdout_tpr'))} | "
                f"{pct(seat.get('holdout_fpr'))} | "
                f"{'yes' if seat.get('seated') else 'NO'} |")
        add("")
        if mono.get("measured_evals_per_sec") is not None:
            add(f"Throughput: **{mono['measured_evals_per_sec']} evals/sec** "
                "(measured, not estimated).")
            add("")

    # ---- adversarial stress ---------------------------------------------
    adv = load("adversarial_stress_results.json")
    add("## Adversarial stress benchmark (`logs/adversarial_stress_results.json`)")
    add("")
    if adv is None:
        add("**NO MEASUREMENT ARTIFACT.** Run `benchmark_adversarial_stress.py`.")
        add("")
    else:
        add(f"Measured {fmt_ts(adv.get('timestamp'))}. Every tier runs the attack "
            "mutant AND a benign pool; the FP column is the false-positive rate "
            "on that benign pool (tiers measured before that column existed "
            "show `n/a`).")
        add("")
        add("| Tier | Intensity | Monolith detection | MoE detection | MoE FP |")
        add("|---|---|---|---|---|")
        for t in adv.get("tiers") or []:
            add(f"| {t.get('tier', 'n/a')} | {t.get('intensity', 'n/a')} | "
                f"{t.get('monolith_detection', 'n/a')}% | "
                f"{t.get('moe_detection', 'n/a')}% | "
                f"{t.get('moe_fpr', 'n/a')} |")
        add("")

    # ---- predictive ------------------------------------------------------
    pred = load("predictive_results.json")
    add("## Predictive module (`logs/predictive_results.json`)")
    add("")
    if pred is None:
        add("**NO MEASUREMENT ARTIFACT.** Run the predictive trainer first.")
        add("")
    else:
        add(f"Window {pred.get('window', '?')} -> horizon "
            f"{pred.get('horizon', '?')}; trained on "
            f"{pred.get('trained_on', 'unknown data')}.")
        add("")
        add("| Holdout slice | n | positives | TPR | FPR | AUC |")
        add("|---|---|---|---|---|---|")
        for name, m in (pred.get("holdout") or {}).items():
            auc = m.get("auc")
            auc_txt = f"{auc:.4f}" if isinstance(auc, (int, float)) else "n/a"
            add(f"| {name} | {m.get('n', '?')} | {m.get('positives', '?')} | "
                f"{pct(m.get('tpr'))} | {pct(m.get('fpr'))} | {auc_txt} |")
        add("")

    add("## Honesty notes")
    add("")
    add("- Numbers never travel from `logs/` to prose by hand: this document")
    add("  is the only rendering the artifacts feed, and CI enforces freshness.")
    add("- The hand-measured pcap table in the README is the deployment-side")
    add("  of the same standard; these artifacts cover training and benchmarks.")
    add("- Seating rules: a specialist holds its council seat only when the")
    add("  promotion gate in `train_honest.py` passes on the holdout split.")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Render docs/MEASURED-PERFORMANCE.md from logs/*.json")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the document is stale vs the artifacts")
    args = ap.parse_args()

    text = render()
    if args.check:
        current = None
        if os.path.exists(DOC):
            with open(DOC, "r", encoding="utf-8") as f:
                current = f.read()
        if current == text:
            print("MEASURED-PERFORMANCE.md is up to date")
            return 0
        print("MEASURED-PERFORMANCE.md is STALE -- run tools/gen_performance_doc.py")
        return 1

    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    with open(DOC, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"Wrote {os.path.relpath(DOC, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
